#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor HDMI-0 -d 1
bspc monitor DP-0 -d 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap           16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a easyeffects desktop='^9'
bspc rule -a noisetorch desktop='^9'
bspc rule -a Thunar state=floating
bspc rule -a qalculate-gtk state=floating

$HOME/.config/polybar/launch_polybar.sh
