#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 2 3 4 5 6 7 8 9
bspc monitor HDMI-0 -d 1

bspc config border_width        1
bspc config window_gap          10
bspc config ignore_ewmh_focus   true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#C8502E
bspc config normal_border_color \#777777

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Qalculate-gtk state=floating follow=on
bspc rule -a Todoist desktop='^8'
bspc rule -a Chromium desktop='^2'
bspc rule -a easyeffects desktop='^9' follow=off
bspc rule -a pavucontrol desktop='^9'
bspc rule -a Blueberry.py desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^4'
bspc rule -a Steam desktop='^4'
bspc rule -a cs2 desktop='^3'
bspc rule -a vibrantLinux state=floating desktop='^8'
bspc rule -a spotify desktop='^1'

export _JAVA_AWT_WM_NONREPARENTING=1

export PATH="~/.local/bin:$PATH"
