#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 2 3 4 5 6
bspc monitor HDMI-0 -d 1

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#15212D

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a pavucontrol state=floating
bspc rule -a qalculate-gtk state=floating
bspc rule -a Thunar state=floating
